# GoReleaser configuration for REP Gateway.
# Triggered by tags matching gateway/v* (e.g. gateway/v0.1.0).
# The workflow sets GORELEASER_CURRENT_TAG to strip the gateway/ prefix.
# See: https://goreleaser.com/customization/

version: 2

project_name: rep-gateway

builds:
  - id: rep-gateway
    main: ./cmd/rep-gateway
    binary: rep-gateway
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    flags:
      - -trimpath

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: ruachtech
    name: rep
  name_template: "Gateway v{{.Version}}"
  header: |
    ## REP Gateway {{.Version}}

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^sdk:'
      - '^cli:'
      - '^codemod:'
      - '^adapters:'
