/**
 * Auto-generated TypeScript definitions for REP variables.
 * Generated by @rep-protocol/cli typegen command.
 * DO NOT EDIT MANUALLY - regenerate with `rep typegen`
 */

declare module "@rep-protocol/sdk" {
  export interface REP {
    /**
     * Get a PUBLIC tier variable value synchronously.
     */
    get(key: "APP_TITLE" | "ENV_NAME" | "API_URL" | "MAX_TODOS"): string | undefined;

    /**
     * Get a SENSITIVE tier variable value asynchronously.
     */
    getSecure(key: "ANALYTICS_KEY"): Promise<string>;

    /**
     * Retrieve all PUBLIC tier variables as a frozen object. Synchronous.
     */
    getAll(): Readonly<Record<string, string>>;

    /**
     * Subscribe to changes for a specific variable.
     */
    onChange(key: string, callback: (newValue: string, oldValue: string | undefined) => void): () => void;

    /**
     * Subscribe to any variable change.
     */
    onAnyChange(callback: (key: string, newValue: string, oldValue: string | undefined) => void): () => void;

    /**
     * Verify payload integrity. Synchronous.
     */
    verify(): boolean;

    /**
     * Get payload metadata.
     */
    meta(): {
      version: string;
      injectedAt: Date;
      integrityValid: boolean;
      publicCount: number;
      sensitiveAvailable: boolean;
      hotReloadAvailable: boolean;
    } | null;
  }

  export const rep: REP;
  export function get(key: string): string | undefined;
  export function getSecure(key: string): Promise<string>;
  export function getAll(): Readonly<Record<string, string>>;
  export function onChange(key: string, callback: (newValue: string, oldValue: string | undefined) => void): () => void;
  export function onAnyChange(callback: (key: string, newValue: string, oldValue: string | undefined) => void): () => void;
  export function verify(): boolean;
  export function meta(): ReturnType<REP["meta"]>;
}
